# SCP is develop by t0206
#settings
#port: 7001 ( You can change it for if you used this port! )
#password is Password is required for connection! ( space is not available ) (also If password is "default", will random gen it.)
port: 7001
password: "default"
#convenients
anti-vpn:
  #check hostname sometimes will detecting VPN ( also Probability is low... )
  check-of-host-name: false
  punish:
    #auto punish => auto kick
    auto-punish: false
    warn-to-chat:
      enable: false
      #if you want send to all players : all
      permission: scp.vpn.warn